name: sensor_med
description: "A new Flutter project."
version: 0.0.1
homepage: ''
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  health:
    git:
      url: https://github.com/justprodev/flutter-plugins
      ref: master
      path: packages/health
  hive: ^2.2.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  screen_state:
    git:
      url: https://github.com/luansilva-tokenlab/flutter-plugins/
      ref: screen-state-ios
      path: packages/screen_state
  synchronized: ^3.1.0+1
  rxdart: ^0.27.7
  geolocator: ^11.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retry: ^3.1.2
  intl: ^0.19.0
  sensors_plus: ^4.0.2
  device_info_plus: ^9.1.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
