// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDek4_zaxghgcdJUzo8Edf01HyUNltNffE',
    appId: '1:349565085218:android:8f9ce3c65c521d3a74cc7b',
    messagingSenderId: '349565085218',
    projectId: 'sensor-med-example-d060e',
    storageBucket: 'sensor-med-example-d060e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Q83sLynDnWsmpzrVw2a1fePMOxYPFL0',
    appId: '1:349565085218:ios:b6081a969a00c67674cc7b',
    messagingSenderId: '349565085218',
    projectId: 'sensor-med-example-d060e',
    storageBucket: 'sensor-med-example-d060e.appspot.com',
    androidClientId: '349565085218-vt0gvaqb7sfc1pn9118biha428qv247g.apps.googleusercontent.com',
    iosClientId: '349565085218-3qtiv1vj83a0j4uqh3qtka51ooj53o10.apps.googleusercontent.com',
    iosBundleId: 'br.com.tokenlab.sensorsMedExample',
  );
}
